//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitidTarjeta
    {
        public int Codigo { get; set; }
        public int CodigoCliente { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string CondicionLaboral { get; set; }
        public decimal IngresoMensual { get; set; }
        public int CodigoTipoTarjeta { get; set; }
    
        public virtual TipoTarjeta TipoTarjeta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
